### ISSUE TITLE
createOxygen doesn't deal with quotes correctly

### ISSUE THREAD

**Issue by jonocarroll** [metrumresearchgroup/sinew#1]
I'm guessing the `createOxygen` Addin doesn't properly handle quotes as I get the following error on this reprex:

```
foo <- function(x) {
  paste0(x, c("[", "2"))
}
# Error in parse(text = obj_name) : <text>:2:15: unexpected '['
# 1: foo <- function(x) {
# 2:   paste0(x, c([
#                  ^
```
where it seems to have removed them internally.

This seems to work fine however when passed with `makeOxygen(foo)`. At a guess, the line responsible might be https://github.com/metrumresearchgroup/sinew/blob/master/R/oxygenAddin.R#L4 .

**Comment by yonicd** [comment]
That is to strip the name of the object name. The intent was to pass into it a compiled function object or name. That is highlight 'foo'.

Like this: 

https://github.com/metrumresearchgroup/sinew/blob/master/Miscellaneous/makeOxygen.gif

**Comment by jonocarroll** [comment]
Ah, now I see. I took from this description:

> The addin createOxygen uses highlighted text in the active document of RStudio as the object argument.

that it was the definition that was to be highlighted, since that's where one wants the roxygen header to go.

Happy to close.

**Comment by yonicd** [comment]
Good point. I'll refine the description
