### ISSUE TITLE
preview doesnt show in interactive addin unless a checkbox is changed

### ISSUE THREAD

**Issue by yonicd** [metrumresearchgroup/sinew#10]
not sure why this is happening

**Comment by yonicd** [comment]
works correct in windows OS/linux but not in mac

**Comment by yonicd** [comment]
and linux , only mac is a problem

**Comment by yonicd** [comment]
@lbusset on a mac it has problems when 5 checkboxes are chosen and on a linux it has problems when 3 checkboxes are chosen, windows no error

**Comment by lbusett** [comment]
I can confirm the problems on Linux. When in "update" mode, the preview only appears when you click/unclick some checkbox.  I can't replicate the "3 checkboxes" behaviour, though.

**Comment by yonicd** [comment]
bug was in sapply in get_oxy had to set simplify=FALSE to force the action
