### ISSUE TITLE
Problem on @export field in uinteractive addin

### ISSUE THREAD

**Issue by lbusett** [metrumresearchgroup/sinew#12]
When using the interactive addin in "Update" mode, the @export field takes an additional "export" string entry.  This leads to errors in building the package. 

![image](https://user-images.githubusercontent.com/4480397/28315724-0a341402-6bc0-11e7-99f9-795764951fd1.png)

**Comment by yonicd** [comment]
sorry. i'll fix that today/tomorrow

**Comment by yonicd** [comment]
fixed
