### ISSUE TITLE
[F] store settings from interactiveOxygen to use via createOxygen

### ISSUE THREAD

**Issue by dpastoor** [metrumresearchgroup/sinew#13]
It'd be pretty sweet to either snapshot (or just have a config file setting) with the fields that are desirable.

I do a good bit of 'package rehab' and and encourage people to dump scripts into project scoped packages. Using sinew is fantastic for that, but is a little more verbose than needed for simple functions. 

Being able to set like a `_sinew.config` either in yaml/toml that would be auto checked-for cascading in say the users home dir and the project dir would be A+. 

something super simple like:

```
add = ["importFrom", "author"] # things actually want
drop = ["seealso", "rdname"] # things from the default that actual don't care about
```

don't neccessarily expect this to be on your priority radar, but putting this up here. If I get some time I can also take a crack and send a PR.

**Comment by yonicd** [comment]
I would be interested to see the direction you suggest. 

That cat was skinned with [sinew::sinew_opts](https://github.com/metrumresearchgroup/sinew/blob/master/R/defaults.R) that have same functionality as knitr::chunk_opts, so you set it once a session and all sinew fns & addin check that by default. I added append to sinew_opts so users can grow the fields they want by default

**Comment by yonicd** [comment]
This is a thread about [sinew_opts](https://github.com/metrumresearchgroup/sinew/issues/9#issuecomment-316545378)

**Comment by dpastoor** [comment]
ah that should be sufficient 👍 

These could also be combined with a quick .onLoad() check for the config to automatically set the opts.


```
.onLoad(pkg) {
    config_file <- file.path(path.expand("~"), "_sinewconfig.yml"))
    if (file.exists(config)) {
         config <- read_yaml(config_file)
         sinew_opts$append(config$add)
    }
}
```

**Comment by yonicd** [comment]
That sounds good. I'll put that in later today. Thanks

**Comment by yonicd** [comment]
added https://github.com/metrumresearchgroup/sinew/commit/7eb3decc61c9b7cd1ab335ffafde6a15375acf4c
