### ISSUE TITLE
Gives Error if there is a file with no functions.

### ISSUE THREAD

**Issue by talgalili** [metrumresearchgroup/sinew#29]
I got:
```
Error: No functions or data frames found in
C:\Dropbox\aaaa good R code\AA - My packages\homework\R\homework.R
```
When running: 
`makeOxyFile('R',overwrite = TRUE)`

had to make a fake function inside.

**Comment by yonicd** [comment]
An informative error message is bad thing? 

https://github.com/metrumresearchgroup/sinew/blob/7657e2fb88ea7e482fe710b3cb1a7850c2a18ae9/R/makeOxyFile.R#L56

**Comment by talgalili** [comment]
Yes. It should be a warning, IMHO :)

**Comment by yonicd** [comment]
try out the branch, if ok i'll merge into the master. https://github.com/metrumresearchgroup/sinew/commit/5c6908d6376a5d9d32ed4912ad55c2e19bc39f55

**Comment by yonicd** [comment]
merged https://github.com/metrumresearchgroup/sinew/commit/90aa9847a73b68f0e9ebf5c539a0d2cb6065acf7
