### ISSUE TITLE
use _sinewconfig.yml to define less fields in `add_fields`

### ISSUE THREAD

**Issue by januz** [metrumresearchgroup/sinew#34]
Thank you for this great package. Very helpful!

Can one *restrict* the tags/fields used by sinew using the yml file? For my current project I don't need certain fields like `@examples`. For example, when I would want to restrict the fields to just the standards plus `@export`, I can do the following

```
sinew_opts$set(list(add_fields='export'))
```

but defining 

```
add_fields = ["export"]
```

in the `_sinewconfig.yml` does not have the same effect. Is one only able to *add* fields in the yml, but not define the whole selection of fields?

Thank you!

**Comment by yonicd** [comment]
That is correct. 

The way it is set up currently the `yml` appends new elements to `add_fields`.

I can add a field to the yml `set_fields`, which can do this.

**Comment by januz** [comment]
> I can add a field to the yml set_fields, which can do this.

That would be great!

**Comment by yonicd** [comment]
you can test this out in this branch https://github.com/metrumresearchgroup/sinew/commit/5932c9feec899156c1995e0a9794f14a6688c975. I'll merge it in a few days.

**Comment by januz** [comment]
works great. Thank you!

**Comment by yonicd** [comment]
merged https://github.com/metrumresearchgroup/sinew/commit/62197f07bc25d242115e903bb7c234c0656dc850
