### ISSUE TITLE
don't define @title and @description tags explicitely

### ISSUE THREAD

**Issue by januz** [metrumresearchgroup/sinew#35]
I like the convention not to define the `@title` and `@description` tags explicitly, but to use the first line as the title, the rest up to the first tag as description as lined out [here](http://r-pkgs.had.co.nz/man.html). I feel like it makes the documentation more readable.

Would it be possible to add an option to choose between the explicit and implicit version? Maybe just something like this in `makeOxygen.R`:

```
if (implicit) {
  header <- c(
      title = "#' FUNCTION_TITLE", "#'",
      description = "#' FUNCTION_DESCRIPTION", "#'"
    )
} else {
  header <- c(
      title = "#' @title FUNCTION_TITLE",
      description = "#' @description FUNCTION_DESCRIPTION"
    )
}
```

Or would that have negative consequences for other functions, e.g. `moga()`?

**Comment by yonicd** [comment]
sorry. they are used in other functions of the package.
